apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-service-config
  namespace: rideshare-data
data:
  PORT: "3005"
  REDIS_TLS: "false"
  DEBUG: "True"
  ALLOWED_ORIGINS: "https://daniel-resume.xyz,https://localhost:3000,https://127.0.0.1:3000"