apiVersion: v1
kind: Service
metadata:
  # This matches exactly what your Driver Service is looking for
  name: swiftride-redis
  namespace: default
spec:
  # This tells Kubernetes to act as an alias/redirect
  type: ExternalName
  # This is the actual destination in the other namespace
  externalName: redis-cluster.rideshare-data.svc.cluster.local